### ISSUE TITLE
confused abour svdnet

### ISSUE THREAD

**Issue by magicffourier** [hsfzxjy/svdnet-pytorch#1]
@hsfzxjy 
Hi, I'm curious about what you implement in svdnet.
In this code,  https://github.com/hsfzxjy/svdnet-pytorch/blob/master/train_svdnet_xent.py#L62-L84. I notice you do some normalization and I'm confused about it.
Can you explain it?

**Comment by hsfzxjy** [comment]
Well, it's a direct translation from the [official MATLAB code](https://github.com/syfafterzy/SVDNet-for-Pedestrian-Retrieval/blob/master/matlab/SVDNet/change_resnet_W.m). It seems to be some unpublished tricks. The link above has more detailed comments.
